/*
 * Auto-generated by nvbpf_py. Edit the Python spec, not this file.
 */

#include <stdint.h>
#include <stdio.h>
#include <string.h>
#include <string>



#define NVBPF_NO_DEFAULT_CALLBACKS
#include "nvbpf.h"








static std::string kernel_name_filter;

struct RecentApiTrace {
    uint64_t event_id = 0;
    bool valid = false;
};
static uint64_t api_event_counter = 0;
static uint64_t peer_sync_hits = 0;
static RecentApiTrace recent_peer_sync;
static uint64_t peer_async_hits = 0;
static RecentApiTrace recent_peer_async;










void nvbit_at_init() {
    setenv("ACK_CTX_INIT_LIMITATION", "1", 1);
    

    if (const char* env = getenv("NVBPF_KERNEL_FILTER")) {
        kernel_name_filter = env;
    }
    
    printf("[NVBPF PEER_COPY_TRACE] Tool loaded\n");
}

void nvbit_at_cuda_event(CUcontext ctx, int is_exit, nvbit_api_cuda_t cbid,
                         const char* name, void* params, CUresult* pStatus) {
    bool is_launch = nvbpf_is_launch_event(cbid);
    if (is_exit) api_event_counter++;
    if (is_exit == 1 && (cbid == API_CUDA_cuMemcpyPeer || cbid == API_CUDA_cuMemcpyPeer_ptds)) {
        peer_sync_hits++;
        recent_peer_sync.event_id = api_event_counter;
        recent_peer_sync.valid = true;
        printf("[NVBPF] api_trace peer_sync event=%s\n", name);
    }
    if (is_exit == 1 && (cbid == API_CUDA_cuMemcpyPeerAsync || cbid == API_CUDA_cuMemcpyPeerAsync_ptsz)) {
        peer_async_hits++;
        recent_peer_async.event_id = api_event_counter;
        recent_peer_async.valid = true;
        printf("[NVBPF] api_trace peer_async event=%s\n", name);
    }
    if (is_launch && is_exit) {
        CUfunction launch_func = nvbpf_get_launch_func(cbid, params);
        const char* launch_name = nvbit_get_func_name(ctx, launch_func);
        if (kernel_name_filter.empty() || strstr(launch_name, kernel_name_filter.c_str()) != nullptr) {
            if (recent_peer_sync.valid && api_event_counter - recent_peer_sync.event_id <= 8) {
                printf("        correlated_peer_sync=1 delta_events=%lu kernel=%s\n",
                       api_event_counter - recent_peer_sync.event_id, launch_name);
            }
            if (recent_peer_async.valid && api_event_counter - recent_peer_async.event_id <= 8) {
                printf("        correlated_peer_async=1 delta_events=%lu kernel=%s\n",
                       api_event_counter - recent_peer_async.event_id, launch_name);
            }
        }
    }

}

void nvbit_at_term() {
    printf("[NVBPF PEER_COPY_TRACE] api_trace peer_sync hits=%lu\n", peer_sync_hits);
    printf("[NVBPF PEER_COPY_TRACE] api_trace peer_async hits=%lu\n", peer_async_hits);
    printf("[NVBPF PEER_COPY_TRACE] Tool terminated\n");
}
