/*
 * Auto-generated by nvbpf_py. Edit the Python spec, not this file.
 */

#include <stdint.h>
#include <stdio.h>
#include <string.h>
#include <string>
#include <pthread.h>
#include <unordered_set>

#define NVBPF_NO_DEFAULT_CALLBACKS
#include "nvbpf.h"

struct samples_event_t {
    uint64_t addr;
    uint32_t sm_id;
    uint32_t warp_id;
    uint32_t cta_id_x;
    uint32_t cta_id_y;
    uint8_t is_load;
};

BPF_ARRAY(sampled, uint64_t, 1);  // loads | stores | Count sampled memory instructions
BPF_RINGBUF(samples, samples_event_t, 4096);  // Sampled memory events

extern "C" __device__ __noinline__ void sampling_mem_events_count_counter(int pred, uint64_t pcounter);
extern "C" __device__ __noinline__ void sampling_mem_events_on_memory(int pred, uint64_t addr, int is_load, uint64_t p_counter_sampled, uint64_t p_event_samples);

static pthread_mutex_t launch_mutex;
static std::unordered_set<CUfunction> already_instrumented;
static std::string kernel_name_filter;
static bool verbose = false;





static bool matches_sampled(Instr* instr) {
    const char* opcode = instr->getOpcodeShort();
    return (instr->isLoad() && instr->getMemorySpace() != InstrType::MemorySpace::CONSTANT) || (instr->isStore());
}

static bool matches_hook_on_memory(Instr* instr) {
    const char* opcode = instr->getOpcodeShort();
    return (instr->isLoad() && instr->getMemorySpace() != InstrType::MemorySpace::CONSTANT) || (instr->isStore());
}

static void reset_state() {
    sampled.reset();
    samples.reset();
}

static void instrument_function_if_needed(CUcontext ctx, CUfunction func) {
    std::vector<CUfunction> related = nvbit_get_related_functions(ctx, func);
    related.push_back(func);
    for (auto f : related) {
        if (!already_instrumented.insert(f).second) continue;
        const std::vector<Instr*>& instrs = nvbit_get_instrs(ctx, f);
        for (auto* instr : instrs) {
            if (matches_sampled(instr)) {
                nvbit_insert_call(instr, "sampling_mem_events_count_counter", IPOINT_BEFORE);
                nvbit_add_call_arg_guard_pred_val(instr);
                nvbit_add_call_arg_const_val64(instr, (uint64_t)&sampled.data[0]);
            }
            if (instr->isLoad() && instr->getMemorySpace() != InstrType::MemorySpace::CONSTANT && matches_hook_on_memory(instr)) {
                nvbit_insert_call(instr, "sampling_mem_events_on_memory", IPOINT_BEFORE);
                nvbit_add_call_arg_guard_pred_val(instr);
                nvbit_add_call_arg_mref_addr64(instr, 0);
                nvbit_add_call_arg_const_val32(instr, 1);
                nvbit_add_call_arg_const_val64(instr, (uint64_t)&sampled.data[0]);
                nvbit_add_call_arg_const_val64(instr, (uint64_t)&samples);
            }
            if (instr->isStore() && matches_hook_on_memory(instr)) {
                nvbit_insert_call(instr, "sampling_mem_events_on_memory", IPOINT_BEFORE);
                nvbit_add_call_arg_guard_pred_val(instr);
                nvbit_add_call_arg_mref_addr64(instr, 0);
                nvbit_add_call_arg_const_val32(instr, 0);
                nvbit_add_call_arg_const_val64(instr, (uint64_t)&sampled.data[0]);
                nvbit_add_call_arg_const_val64(instr, (uint64_t)&samples);
            }
        }
    }
}

void nvbit_at_init() {
    setenv("ACK_CTX_INIT_LIMITATION", "1", 1);
    setenv("CUDA_MANAGED_FORCE_DEVICE_ALLOC", "1", 1);
    pthread_mutex_init(&launch_mutex, nullptr);
    if (const char* env = getenv("NVBPF_KERNEL_FILTER")) {
        kernel_name_filter = env;
    }
    verbose = getenv("NVBPF_VERBOSE") != nullptr;
    printf("[NVBPF SAMPLING_MEM_EVENTS] Tool loaded\n");
}

void nvbit_at_cuda_event(CUcontext ctx, int is_exit, nvbit_api_cuda_t cbid,
                         const char* name, void* params, CUresult* pStatus) {
    bool is_launch = nvbpf_is_launch_event(cbid);

    if (!is_launch) return;
    CUfunction func = nvbpf_get_launch_func(cbid, params);
    const char* func_name = nvbit_get_func_name(ctx, func);

    if (!is_exit) {
        bool match = kernel_name_filter.empty() ||
                     strstr(func_name, kernel_name_filter.c_str()) != nullptr;
        pthread_mutex_lock(&launch_mutex);
        if (match) {
            instrument_function_if_needed(ctx, func);
            reset_state();
            nvbit_enable_instrumented(ctx, func, true);
        } else {
            nvbit_enable_instrumented(ctx, func, false);
        }
        if (!match) pthread_mutex_unlock(&launch_mutex);
    } else {
        cudaDeviceSynchronize();
        if (!kernel_name_filter.empty() &&
            strstr(func_name, kernel_name_filter.c_str()) == nullptr) {
            return;
        }
        printf("[NVBPF] %s\n", func_name);
        printf("        sampled=%lu\n", *sampled.lookup(0));

        uint64_t samples_count = 0;
        if (verbose) {
            samples_count = samples.consume([](samples_event_t* evt) {
                printf("          samples addr=%lu sm_id=%u warp_id=%u cta_id_x=%u cta_id_y=%u is_load=%u\n", (unsigned long)evt->addr, (unsigned)evt->sm_id, (unsigned)evt->warp_id, (unsigned)evt->cta_id_x, (unsigned)evt->cta_id_y, (unsigned)evt->is_load);
            });
        } else {
            samples_count = samples.consume([](samples_event_t*) {});
        }
        printf("        samples_events=%lu dropped=%lu\n",
               samples_count, samples.dropped);

        pthread_mutex_unlock(&launch_mutex);
    }
}

void nvbit_at_term() {

    printf("[NVBPF SAMPLING_MEM_EVENTS] Tool terminated\n");
}
