/*
 * Auto-generated by nvbpf_py. Edit the Python spec, not this file.
 */

#include <stdint.h>
#include "nvbpf_helpers.h"
#include "nvbpf_maps.h"
#include "utils/utils.h"

struct samples_event_t {
    uint64_t addr;
    uint32_t sm_id;
    uint32_t warp_id;
    uint32_t cta_id_x;
    uint32_t cta_id_y;
    uint8_t is_load;
};

extern "C" __device__ __noinline__ void sampling_mem_events_count_counter(int pred, uint64_t pcounter) {
    const int active_mask = __ballot_sync(__activemask(), 1);
    const int predicate_mask = __ballot_sync(__activemask(), pred);
    const int laneid = get_laneid();
    const int first_laneid = __ffs(active_mask) - 1;
    if (first_laneid == laneid && __popc(predicate_mask) > 0) {
        atomicAdd((unsigned long long*)pcounter, 1ULL);
    }
}

extern "C" __device__ __noinline__ void sampling_mem_events_on_memory(int pred, uint64_t addr, int is_load, uint64_t p_counter_sampled, uint64_t p_event_samples) {
    const int active_mask = __ballot_sync(__activemask(), 1);
    const int predicate_mask = __ballot_sync(__activemask(), pred);
    const int laneid = get_laneid();
    const int first_laneid = __ffs(active_mask) - 1;
    const int active_lanes = __popc(predicate_mask);
    const uint32_t sm_id = bpf_get_current_sm_id();
    const uint32_t warp_id = bpf_get_current_warp_id();
    const uint32_t cta_id_x = blockIdx.x;
    const uint32_t cta_id_y = blockIdx.y;
    const uint32_t cta_id_z = blockIdx.z;
    if (first_laneid != laneid) return;
    uint64_t* counter_sampled = (uint64_t*)p_counter_sampled;
    auto* ring_samples = (BpfRingBufMap<samples_event_t, 4096>*)p_event_samples;
    if ((active_lanes == 0)) {
        return;
    }
    if (((addr & 63) != 0)) {
        return;
    }
    atomicAdd((unsigned long long*)counter_sampled, 1ULL);
    samples_event_t evt{};
    evt.addr = addr;
    evt.sm_id = sm_id;
    evt.warp_id = warp_id;
    evt.cta_id_x = cta_id_x;
    evt.cta_id_y = cta_id_y;
    evt.is_load = is_load;
    ring_samples->output(&evt);
}
